In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [2]:
#Input Training Data
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Output or Targets 
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
#Covert inputs and Targets into Tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
#Linear Regression Model
#Weights and Biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

#torch.randn creates a tensor with the given shape, with elements picked randomly from a normal distribution with mean 0 and standard deviation 1.#


tensor([[ 0.8223,  0.5274,  0.5275],
        [ 0.3356, -0.9028,  0.6906]], requires_grad=True)
tensor([1.7346, 0.4702], requires_grad=True)


In [6]:
def model (x):
    return x@w.t() + b

#@ represents matrix multiplication in PyTorch, and the .t method returns the transpose of a tensor.

In [7]:
#Generate Preedictions
preds = model(inputs)
print(preds)

tensor([[119.7853,  -5.8251],
        [156.7411,  -4.2413],
        [174.5484, -51.2561],
        [127.8089,  21.4305],
        [146.0349, -14.7030]], grad_fn=<AddBackward0>)


In [8]:
#Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
#Defining MSE Loss Function
def mse(a, b):
    diff = a-b
    return torch.sum (diff*diff) / diff.numel()

In [10]:
#Compute Loss
loss = mse(preds, targets)
print(loss)

tensor(9483.2803, grad_fn=<DivBackward0>)


In [11]:
#Compute Gradients
loss.backward()

# The gradients are stored in the .grad property of the respective tensors. Note that the derivative of the loss w.r.t. the weights matrix is itself a matrix with the same dimensions.

In [12]:
#Gradients for Weights
print(w)
print(w.grad)

tensor([[ 0.8223,  0.5274,  0.5275],
        [ 0.3356, -0.9028,  0.6906]], requires_grad=True)
tensor([[  6028.6787,   5412.6895,   3547.8752],
        [ -8391.2129, -10507.3613,  -6123.6113]])


In [13]:
w
w.grad

tensor([[  6028.6787,   5412.6895,   3547.8752],
        [ -8391.2129, -10507.3613,  -6123.6113]])

In [14]:
#Calculating new loss
loss = mse(preds, targets)
print(loss)

tensor(9483.2803, grad_fn=<DivBackward0>)


In [15]:
#Adjust Weights and Biases
lr = 1e-5
with torch.no_grad():
    w.sub_(w.grad*lr)
    b.sub_(b.grad*lr)

In [16]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [17]:
#Train the model using SGD
preds = model(inputs)
print(preds)

tensor([[110.2316,   9.9746],
        [144.2206,  16.5614],
        [159.9920, -26.3232],
        [118.0188,  36.7745],
        [134.1947,   5.4616]], grad_fn=<AddBackward0>)


In [18]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(6781.8799, grad_fn=<DivBackward0>)


In [19]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 5044.9263,  4362.6709,  2898.3867],
        [-6756.8086, -8742.1982, -5036.3882]])
tensor([ 57.1315, -83.5102])


In [20]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [21]:
print(w)
print(b)

tensor([[ 0.7116,  0.4297,  0.4631],
        [ 0.4871, -0.7103,  0.8022]], requires_grad=True)
tensor([1.7334, 0.4721], requires_grad=True)


In [22]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(4956.5303, grad_fn=<DivBackward0>)


In [23]:
# Train for 100 epochs
for i in range(100):
#Train for multiple epochs
#def update():
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [24]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(345.7936, grad_fn=<DivBackward0>)


In [25]:
#Predictions
preds

tensor([[ 62.4136,  76.8164],
        [ 83.9017, 107.4276],
        [106.4063, 107.1300],
        [ 49.7195,  74.6157],
        [ 88.4975, 109.0444]], grad_fn=<AddBackward0>)

In [26]:
#Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
# LINEAR REGRESSION USING PYTORCH BUILTINS

In [27]:
import torch.nn as nn

In [28]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [29]:
from torch.utils.data import TensorDataset

In [30]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [31]:
from torch.utils.data import DataLoader

In [32]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [33]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [101.,  44.,  37.],
        [ 74.,  66.,  43.],
        [ 73.,  66.,  44.],
        [ 87., 135.,  57.]])
tensor([[103., 119.],
        [ 21.,  38.],
        [ 57.,  69.],
        [ 57.,  69.],
        [118., 134.]])


In [34]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5533,  0.3572, -0.5683],
        [ 0.4134,  0.2929,  0.1853]], requires_grad=True)
Parameter containing:
tensor([ 0.3025, -0.4652], requires_grad=True)


In [35]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5533,  0.3572, -0.5683],
         [ 0.4134,  0.2929,  0.1853]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3025, -0.4652], requires_grad=True)]

In [36]:
# Generate predictions
preds = model(inputs)
preds

tensor([[40.1916, 57.3076],
        [45.7185, 74.7917],
        [63.3458, 85.5008],
        [51.0758, 61.1544],
        [32.9926, 69.1520],
        [40.3877, 57.4280],
        [44.7930, 74.6841],
        [63.3309, 86.0995],
        [50.8797, 61.0339],
        [31.8709, 68.9239],
        [39.2661, 57.1999],
        [45.9146, 74.9122],
        [64.2713, 85.6084],
        [52.1975, 61.3825],
        [32.7964, 69.0315]], grad_fn=<AddmmBackward>)

In [37]:
# Import nn.functional
import torch.nn.functional as F

# Define loss function
loss_fn = F.mse_loss

loss = loss_fn(model(inputs), targets)
print(loss)

tensor(1654.0220, grad_fn=<MseLossBackward>)


In [38]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [39]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [40]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 247.7769
Epoch [20/100], Loss: 396.0662
Epoch [30/100], Loss: 292.2541
Epoch [40/100], Loss: 139.6670
Epoch [50/100], Loss: 237.2041
Epoch [60/100], Loss: 134.1498
Epoch [70/100], Loss: 125.0743
Epoch [80/100], Loss: 57.9666
Epoch [90/100], Loss: 116.6432
Epoch [100/100], Loss: 99.5789


In [41]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.9131,  71.6194],
        [ 76.9535,  98.1964],
        [126.2931, 135.7276],
        [ 31.5225,  45.3418],
        [ 86.8587, 109.9374],
        [ 57.7654,  70.6609],
        [ 75.7960,  97.7986],
        [126.0881, 136.1107],
        [ 32.6703,  46.3002],
        [ 86.8490, 110.4980],
        [ 57.7557,  71.2215],
        [ 75.8057,  97.2380],
        [127.4506, 136.1254],
        [ 31.5322,  44.7812],
        [ 88.0065, 110.8958]], grad_fn=<AddmmBackward>)

In [42]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [44]:
# Tryinhnew Data
model(torch.tensor([[75, 63, 44.]]))

tensor([[54.4101, 68.4349]], grad_fn=<AddmmBackward>)