In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [2]:
#Input Training Data
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Output or Targets 
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
#Covert inputs and Targets into Tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
#Linear Regression Model
#Weights and Biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

#torch.randn creates a tensor with the given shape, with elements picked randomly from a normal distribution with mean 0 and standard deviation 1.#


tensor([[ 0.7657, -2.1983, -0.9779],
        [-1.1067,  1.5160,  2.6091]], requires_grad=True)
tensor([-1.3641,  0.2328], requires_grad=True)


In [6]:
def model (x):
    return x@w.t() + b

#@ represents matrix multiplication in PyTorch, and the .t method returns the transpose of a tensor.

In [7]:
#Generate Preedictions
preds = model(inputs)
print(preds)

tensor([[-134.7988,  133.2056],
        [-187.7153,  199.9114],
        [-286.0306,  258.4201],
        [ -53.9663,   49.0728],
        [-228.0154,  252.0412]], grad_fn=<AddBackward0>)


In [8]:
#Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
#Defining MSE Loss Function
def mse(a, b):
    diff = a-b
    return torch.sum (diff*diff) / diff.numel()

In [10]:
#Compute Loss
loss = mse(preds, targets)
print(loss)

tensor(43535.8359, grad_fn=<DivBackward0>)


In [11]:
#Compute Gradients
loss.backward()

# The gradients are stored in the .grad property of the respective tensors. Note that the derivative of the loss w.r.t. the weights matrix is itself a matrix with the same dimensions.

In [12]:
#Gradients for Weights
print(w)
print(w.grad)

tensor([[ 0.7657, -2.1983, -0.9779],
        [-1.1067,  1.5160,  2.6091]], requires_grad=True)
tensor([[-20841.5410, -25149.7207, -14975.1484],
        [  6987.5542,   8607.2734,   5216.4238]])


In [13]:
w
w.grad

tensor([[-20841.5410, -25149.7207, -14975.1484],
        [  6987.5542,   8607.2734,   5216.4238]])

In [14]:
#Calculating new loss
loss = mse(preds, targets)
print(loss)

tensor(43535.8359, grad_fn=<DivBackward0>)


In [15]:
#Adjust Weights and Biases
lr = 1e-5
with torch.no_grad():
    w.sub_(w.grad*lr)
    b.sub_(b.grad*lr)

In [16]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [17]:
#Train the model using SGD
preds = model(inputs)
print(preds)

tensor([[ -96.2923,  120.0939],
        [-137.0311,  182.6389],
        [-225.5098,  237.7808],
        [ -16.3502,   36.3134],
        [-179.0059,  235.3044]], grad_fn=<AddBackward0>)


In [18]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(30409.6133, grad_fn=<DivBackward0>)


In [19]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-16860.1309, -20855.2520, -12328.6992],
        [  5631.3813,   7143.3706,   4314.4253]])
tensor([-207.0379,   70.4263])


In [20]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [21]:
print(w)
print(b)

tensor([[ 1.1428, -1.7382, -0.7049],
        [-1.2329,  1.3585,  2.5138]], requires_grad=True)
tensor([-1.3595,  0.2312], requires_grad=True)


In [22]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(21550.9258, grad_fn=<DivBackward0>)


In [25]:
# Train for 100 epochs
for i in range(100): update()
#Train for multiple epochs
#def update():
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

UnboundLocalError: local variable 'w' referenced before assignment

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

In [ ]:
#Predictions
preds

In [ ]:
#Targets
targets

In [ ]:
import torch.nn as nn